"""
Django settings for root_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from dotenv import load_dotenv
from os import getenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment files
# Dockerfile provides environment variables from .env to Django
# If running without Docker, may need to read from .env file
load_dotenv(dotenv_path='.env', override=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('SECRET_KEY', default='dinosecretkey')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(getenv('DEBUG', default=True))

ALLOWED_HOSTS = getenv(
    'ALLOWED_HOSTS', default='localhost,127.0.0.1'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dinosaur',
    'encyclosaurus',
    'user',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware', # Must be first
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'root_project.middleware.AuthenticationMiddleware',
]

# Prevent map tiles from being blocked when HTTP: https://wiki.openstreetmap.org/wiki/Referer
SECURE_REFERRER_POLICY = 'origin-when-cross-origin'

ROOT_URLCONF = 'root_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'root_project.context_processors.auth_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'root_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# SECURITY WARNING: keep the database credentials secret!
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.{}'.format(
            getenv('DATABASE_ENGINE', default='postgresql')
        ),
        'NAME': getenv('DATABASE_NAME', default='dinodb'),
        'USER': getenv('DATABASE_USER', default='dinouser'),
        'PASSWORD': getenv('DATABASE_PASSWORD', default='dinopassword'),
        'HOST': getenv('DATABASE_HOST', default='db'),
        'PORT': getenv('DATABASE_PORT', default='5432'),
    }
}


# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': getenv('LOG_LEVEL', default='info').upper(),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 1 day in seconds
