# Generated by Django 4.2.20 on 2025-04-12 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.CharField(default='Clade', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dinosaur.clade')),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('discoverer_name', models.CharField(max_length=100)),
                ('discoverer_year', models.IntegerField()),
                ('range_start', models.FloatField()),
                ('range_end', models.FloatField()),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('gait', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('clade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinosaur.clade')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('details', models.TextField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DinosaurLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur.dinosaur')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur.location')),
            ],
            options={
                'unique_together': {('dinosaur', 'location')},
            },
        ),
    ]
