# Generated by Django 4.2.20 on 2025-04-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='SiteManager',
            new_name='site_manager',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
