# Generated by Django 4.2.20 on 2025-04-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_sitemanager_user_site_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('institution', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='site_manager',
            new_name='SiteManager',
        ),
    ]
